# Generated by Django 3.2.12 on 2022-06-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField()),
                ('etc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Praise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('img_path', models.TextField()),
                ('instruments', models.TextField()),
                ('chord', models.TextField()),
                ('key_up', models.TextField()),
            ],
        ),
    ]
