# Generated by Django 3.2.12 on 2022-06-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praise',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(),
        ),
    ]
