# Generated by Django 3.2.12 on 2022-06-03 00:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0003_alter_praise_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
