# Generated by Django 3.2.12 on 2022-06-03 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0004_alter_date_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Date',
        ),
    ]
