# Generated by Django 3.2.12 on 2022-06-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0005_delete_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='chord',
            field=models.CharField(blank=True, choices=[('C', 'C'), ('D', 'D'), ('Eb', 'Eb'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('A', 'A'), ('Bb', 'Bb'), ('B', 'B')], max_length=3),
        ),
        migrations.AlterField(
            model_name='praise',
            name='key_up',
            field=models.CharField(choices=[('X', 'No'), ('O', 'Yes')], default='X', max_length=3),
        ),
    ]
