# Generated by Django 3.2.12 on 2022-06-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0006_auto_20220606_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='img_path',
            field=models.TextField(blank=True),
        ),
    ]
