# Generated by Django 3.2.12 on 2022-06-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0008_praise_after_praise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praise',
            name='after_praise',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
