# Generated by Django 3.2.12 on 2022-06-06 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0009_alter_praise_after_praise'),
    ]

    operations = [
        migrations.RenameField(
            model_name='praise',
            old_name='after_praise',
            new_name='note',
        ),
    ]
