# Generated by Django 3.2.13 on 2022-07-29 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0010_rename_after_praise_praise_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praise',
            name='img_path',
        ),
        migrations.AddField(
            model_name='praise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='praise'),
        ),
        migrations.AlterField(
            model_name='praise',
            name='instruments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='praise',
            name='key_up',
            field=models.TextField(default='X', max_length=3),
        ),
        migrations.AlterField(
            model_name='praise',
            name='note',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
